/*
# FinPilot: Core schema (single-tenant demo, auth-ready)

## Purpose
FinPilot is an AI-powered personal financial decision engine for the Indian market.
This migration creates the core data model and seeds deterministic demo data so the
application works immediately without bank integrations.

## Tables created
1. `profiles` — user display profile (name, avatar). One row per user.
2. `financial_profiles` — the user's "Financial DNA": risk profile, horizon, goal,
   experience, liquidity preference, plus monthly income band. Derived from onboarding
   answers. One row per user.
3. `goals` — financial goals with target amount, current amount, and target year.
4. `transactions` — monthly income, expenses, savings, investment cashflows (demo).
5. `portfolio_holdings` — investment holdings across asset classes & platforms.
6. `recommendations` — prioritized financial actions generated by the deterministic
   engine, each with what happened, why it matters, and a fix path.

## Security
- This is a single-tenant demo app with NO sign-in screen yet, so RLS policies use
  `TO anon, authenticated` with `USING (true)` — the data is intentionally shared/public
  for the demo. When auth is added later, these policies should be replaced with
  `auth.uid()`-based ownership checks.
- RLS enabled on every table.

## Notes
- All monetary amounts are stored in whole rupees (integer) for the demo.
- The deterministic financial engine runs client-side; the database stores inputs and
  generated recommendations, not computed scores.
- `IF NOT EXISTS` used for idempotency; policies dropped before recreate.
*/

CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL DEFAULT 'Aarav',
  greeting_name text NOT NULL DEFAULT 'Aarav',
  avatar_url text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_read_profiles" ON profiles;
CREATE POLICY "anon_read_profiles" ON profiles FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_profiles" ON profiles;
CREATE POLICY "anon_insert_profiles" ON profiles FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_profiles" ON profiles;
CREATE POLICY "anon_update_profiles" ON profiles FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_profiles" ON profiles;
CREATE POLICY "anon_delete_profiles" ON profiles FOR DELETE TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS financial_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
  risk_profile text NOT NULL DEFAULT 'Moderate',
  risk_score integer NOT NULL DEFAULT 50,
  investment_horizon text NOT NULL DEFAULT '3-7 years',
  primary_goal text NOT NULL DEFAULT 'Build Wealth',
  experience text NOT NULL DEFAULT 'Intermediate',
  liquidity_preference text NOT NULL DEFAULT 'Balanced',
  monthly_income_band text NOT NULL DEFAULT '₹50,000 - ₹1,00,000',
  monthly_income_estimated integer NOT NULL DEFAULT 85000,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE financial_profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_read_financial_profiles" ON financial_profiles;
CREATE POLICY "anon_read_financial_profiles" ON financial_profiles FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_financial_profiles" ON financial_profiles;
CREATE POLICY "anon_insert_financial_profiles" ON financial_profiles FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_financial_profiles" ON financial_profiles;
CREATE POLICY "anon_update_financial_profiles" ON financial_profiles FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_financial_profiles" ON financial_profiles;
CREATE POLICY "anon_delete_financial_profiles" ON financial_profiles FOR DELETE TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS goals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
  name text NOT NULL,
  target_amount integer NOT NULL,
  current_amount integer NOT NULL DEFAULT 0,
  target_year integer NOT NULL,
  monthly_contribution integer NOT NULL DEFAULT 0,
  icon text NOT NULL DEFAULT 'home',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_read_goals" ON goals;
CREATE POLICY "anon_read_goals" ON goals FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_goals" ON goals;
CREATE POLICY "anon_insert_goals" ON goals FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_goals" ON goals;
CREATE POLICY "anon_update_goals" ON goals FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_goals" ON goals;
CREATE POLICY "anon_delete_goals" ON goals FOR DELETE TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
  month text NOT NULL,
  income integer NOT NULL DEFAULT 0,
  expenses integer NOT NULL DEFAULT 0,
  savings integer NOT NULL DEFAULT 0,
  investments integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_read_transactions" ON transactions;
CREATE POLICY "anon_read_transactions" ON transactions FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_transactions" ON transactions;
CREATE POLICY "anon_insert_transactions" ON transactions FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_transactions" ON transactions;
CREATE POLICY "anon_update_transactions" ON transactions FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_transactions" ON transactions;
CREATE POLICY "anon_delete_transactions" ON transactions FOR DELETE TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS portfolio_holdings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
  name text NOT NULL,
  asset_class text NOT NULL,
  platform text NOT NULL,
  current_value integer NOT NULL,
  units numeric,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE portfolio_holdings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_read_portfolio_holdings" ON portfolio_holdings;
CREATE POLICY "anon_read_portfolio_holdings" ON portfolio_holdings FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_portfolio_holdings" ON portfolio_holdings;
CREATE POLICY "anon_insert_portfolio_holdings" ON portfolio_holdings FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_portfolio_holdings" ON portfolio_holdings;
CREATE POLICY "anon_update_portfolio_holdings" ON portfolio_holdings FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_portfolio_holdings" ON portfolio_holdings;
CREATE POLICY "anon_delete_portfolio_holdings" ON portfolio_holdings FOR DELETE TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS recommendations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
  slug text NOT NULL,
  title text NOT NULL,
  category text NOT NULL,
  priority integer NOT NULL DEFAULT 1,
  what_happened text NOT NULL,
  why_it_matters text NOT NULL,
  what_to_do text NOT NULL,
  cta_label text NOT NULL DEFAULT 'See how to fix this',
  metric_value text,
  metric_label text,
  severity text NOT NULL DEFAULT 'warning',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE recommendations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_read_recommendations" ON recommendations;
CREATE POLICY "anon_read_recommendations" ON recommendations FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_recommendations" ON recommendations;
CREATE POLICY "anon_insert_recommendations" ON recommendations FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_recommendations" ON recommendations;
CREATE POLICY "anon_update_recommendations" ON recommendations FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_recommendations" ON recommendations;
CREATE POLICY "anon_delete_recommendations" ON recommendations FOR DELETE TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_goals_user
ON goals(user_id);

CREATE INDEX IF NOT EXISTS idx_transactions_user
ON transactions(user_id);

CREATE INDEX IF NOT EXISTS idx_portfolio_holdings_user
ON portfolio_holdings(user_id);

CREATE INDEX IF NOT EXISTS idx_recommendations_user
ON recommendations(user_id);

CREATE INDEX IF NOT EXISTS idx_financial_profiles_user
ON financial_profiles(user_id);